### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by madmax983** [madmax983/Lightning-Data-Grid#3]
A configurable global search in the toolbar.

**Comment by siddharatha** [comment]
I am using a [strike datagrid](http://www.lightningstrike.io/#!/strikeDataGrid) where I have implemented a custom search just to narrow the results.


````
// dataGridWrapperHelper.js 

 performSearch:function(component){
        var helper = this;
        this.debouncedSearch = _.debounce($A.getCallback(function(component){          
            var data = component.get('v.data');          
            var unfilteredRows = component.get('v.unfilteredRows');
            var search = _.toLower(component.get('v.search'));         
            if(_.isEmpty(search))
                data.rows=_.clone(unfilteredRows);        
            else
                data.rows = _.sampleSize(_.filter(unfilteredRows,function(result){return _.toLower(JSON.stringify(_.values(result))).indexOf(search) >=0}),50);                      
            component.set('v.data',data);
            component.find('dataGrid').set('v.data',data);
            helper.prepareChartData(component);
            helper.stopWaiting(component);
        }),250, { 'maxWait': 1000 });
    },
    debouncedSearch:function(component){
        
    },
````

and the controller defining the debounce function 
````
// dataGridWrapperController.js 

 doInit: function(component,event,helper){        
        helper.performSearch(component);        
    },

````

may be this can help ?

**Comment by madmax983** [comment]
@siddharatha I am working on this right now, so thank you for the help. One of the guiding principles for his grid is to allow extensibility, so the general concept I have right now is to allow a hook into changing the view with a GridViewMutation event. You send the type of mutation along with the mutated (filtered or searched data), and the grid will take care of updating the view for you. This will allow #5 and #6  to utilize the same event interface. 

Let me get what I've been working on committed and let me know what you think
