### ISSUE TITLE
can't reinitialize the DataGrid with new data

### ISSUE THREAD

**Issue by alexanderyhapcv** [madmax983/Lightning-Data-Grid#43]
When trying to update data attribute and calling init() again Grid gets stuck loading

**Comment by madmax983** [comment]
Should have a PR to fix this later tonight. I think I am going to introduce a new refresh method, although it will mostly involve fixes to the existing init methods. Just feels more idiomatic to call refresh in this use case, rather then calling init again (unless we changed it to dataInit or something like that?). Thoughts?

**Comment by madmax983** [comment]
With the refresh method, you should be able to update the data attribute on the grid, call refresh, and have your changes propagate. Let me know if you find anymore issues!

**Comment by alexanderyhapcv** [comment]
wow! thanks for a quick response @madmax983 this is exactly what I needed!
