### ISSUE TITLE
Missing additionalView attribute on DataGrid cmp

### ISSUE THREAD

**Issue by alexanderyhapcv** [madmax983/Lightning-Data-Grid#8]
`<aura:iteration items="{!v.additionalView}" var="item" indexVar="index">`

additionalView array is missing

**Comment by madmax983** [comment]
Thank for opening the issue @cv-alexanderyhap. I'm currently working on doing an update on this project adding in Lightning Test Service and SFDX. This will be addressed in that update. The additional view attribute was an experiment that didn't really pan out.

Thanks for looking at this repo!
