### ISSUE TITLE
Access Check Failed! AttributeSet.get(): attribute 'columnName' of Component 'Cell' is not visible 

### ISSUE THREAD

**Issue by rajarak12** [madmax983/Lightning-Data-Grid#9]
Access Check Failed! AttributeSet.get(): attribute 'columnName' of Component 'Cell' is not visible 

I believe it is 'Column' instead of 'columnName'?

<th aura:id="cell" id="{!'ltng-grid-col-' + v.**columnName** + '-' + 'row-' + v.rowIndex}"
            class="{!v.isDirty ? 'slds-tree__item slds-cell-edit slds-is-edited' : 'slds-tree__item slds-cell-edit'}"
            data-label="{!v.column.name}"
            onkeypress="{!c.handleKeyPress}"
            tabindex="0">

 <td aura:id="cell" id="{!'ltng-grid-col-' + v.**columnName** + '-' + 'row-' + v.rowIndex}"
                data-label="{!v.column.name}"
                role="gridcell"
                class="{!v.isDirty ? 'slds-cell-edit slds-is-edited' : 'slds-cell-edit'}"
                onkeypress="{!c.handleKeyPress}"
                tabindex="0">

**Comment by madmax983** [comment]
@rajarak12 Thanks for opening this issue. I will address this in a forthcoming update.

**Comment by madmax983** [comment]
Issue is coming from Cell.cmp. 

Offenders are: 

`<th aura:id="cell" id="{!'ltng-grid-col-' + v.columnName + '-' + 'row-' + v.rowIndex}"`

And

`<td aura:id="cell" id="{!'ltng-grid-col-' + v.columnName + '-' + 'row-' + v.rowIndex}"`

These need to change to v.column.name. These dynamic id's are intended as hooks for QA Automation testing.
